classDiagram
    direction RL
    class User {
        +Int id
        +String name
        +String email
        +String password
    }

    class Role {
        +Int id
        +String name
    }

    class TaskList {
        +Int id
        +String title
        +Date creationDate
    }

    class Task {
        +Int id
        +String title
        +String description
        +Boolean status
        +Date creationDate
        +Date dueDate
    }

    User "1" -- "*" TaskList 
    TaskList "1" -- "*" Task 
    Role "1" -- "*" User
